<?php

namespace Incentives\BaseBundle\Repository;

/**
 * CorreosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CorreosRepository extends \Doctrine\ORM\EntityRepository
{
}
