parameters:
#    incentives_operaciones.example.class: Incentives\OperacionesBundle\Example

services:
#    incentives_operaciones.example:
#        class: %incentives_operaciones.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
