incentives_autenticacion_login:
    path:  /autenticacion/
    defaults: { _controller: IncentivesBaseBundle:Autenticacion:login }

logout:
    path:   /logout

usuarios:
   path:  /usuarios
   defaults: { _controller: IncentivesBaseBundle:Usuarios:listado }

recordar_password:
   path:  /recordar
   defaults: { _controller: IncentivesBaseBundle:Usuarios:recordar }

usuarios_nuevo:
   path:  /usuarios/nuevo
   defaults: { _controller: IncentivesBaseBundle:Usuarios:nuevo }

usuarios_editar:
   path:  /usuarios/editar/{id}
   defaults: { _controller: IncentivesBaseBundle:Usuarios:editar, id: null }

usuario_nombre:
   path:  /usuario/nombre/
   defaults: { _controller: IncentivesBaseBundle:Usuarios:nombre }

usuario_correo_ingreso:
    path:  /usuario/correoingreso/{id}
    defaults: { _controller: IncentivesBaseBundle:Usuarios:correoingreso, id: null }
    requirements:
        id:  \d+

usuario_actualizarpassword:
    path:  /pass/{id}/{token}
    defaults: { _controller: IncentivesBaseBundle:Usuarios:actualizarpassword, id: null, token: null }
    requirements:
        id:  \d+

campos_ciudad:
   path:  /campos/ciudad/{id}
   defaults: { _controller: IncentivesBaseBundle:Campos:ciudad, id: null }
   requirements:
        id:  \d+

campos_capitales:
   path:  /campos/capitales/{id}
   defaults: { _controller: IncentivesBaseBundle:Campos:capitales, id: null }
   requirements:
        id:  \d+

campos_departamento:
   path:  /campos/departamento/{id}
   defaults: { _controller: IncentivesBaseBundle:Campos:departamento, id: null }
   requirements:
        id:  \d+

ciudad_buscar:
   path:  /ciudad/buscar
   defaults: { _controller: IncentivesBaseBundle:Campos:CiudadBuscar}
   
ciudad_campos:
   path:  /ciudad/campos
   defaults: { _controller: IncentivesBaseBundle:Campos:CiudadCampos}

correoEnviar:
   path:  /correo/enviar
   defaults: { _controller: IncentivesBaseBundle:Correos:correoEnviar }

campos_exporar:
   path:  /campos/exportar
   defaults: { _controller: IncentivesBaseBundle:Campos:exportar}

menu:
   path:  /menu
   defaults: { _controller: IncentivesBaseBundle:Menu:menuPrincipal }
