parameters:
#    incentives_base.example.class: Incentives\BaseBundle\Example

services:
#    incentives_base.example:
#        class: %incentives_base.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
