<?php

namespace Incentives\InventarioBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CostosLogisticaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CostosLogisticaRepository extends EntityRepository
{
}
