producto:
    path:  /producto
    defaults: { _controller: IncentivesCatalogoBundle:Producto:listado}

producto_listadouniversal:
    path:  /producto/listadouniversal
    defaults: { _controller: IncentivesCatalogoBundle:Producto:listadouniversal }

producto_nuevo:
    path:  /producto/nuevo
    defaults: { _controller: IncentivesCatalogoBundle:Producto:nuevo}

producto_editar:
    path:  /producto/editar/{id}
    defaults: { _controller: IncentivesCatalogoBundle:Producto:editar, id: null }
    requirements:
        id:  \d+

producto_datos:
    path:  /producto/datos/{id}
    defaults: { _controller: IncentivesCatalogoBundle:Producto:datos, id: null }
    requirements:
        id:  \d+

producto_estado:
    path:  /producto/estado/{id}
    defaults: { _controller: IncentivesCatalogoBundle:Producto:estado, id: null }
    requirements:
        id:  \d+

producto_agregarimagen:
    path:  /producto/imagen/agregar/{id}
    defaults: { _controller: IncentivesCatalogoBundle:Producto:cargaImagen, id: null }
    requirements:
        id:  \d+

producto_estadoimagen:
    path:  /producto/imagen/estado/{id}
    defaults: { _controller: IncentivesCatalogoBundle:Producto:estadoImagen, id: null }
    requirements:
        id:  \d+

producto_imagenmasivo:
    path:  /producto/imagen/masivo
    defaults: { _controller: IncentivesCatalogoBundle:Producto:masivoImagen }

premios_imagenmasivo_combos:
    path:  /premios/imagencombos/{catalogo}
    defaults: { _controller: IncentivesCatalogoBundle:Premios:masivoImagenCombos , catalogo: null}

producto_agregarprecio:
    path:  /producto/precio/agregar/{id}
    defaults: { _controller: IncentivesCatalogoBundle:Producto:agregarPrecio, id: null }
    requirements:
        id:  \d+

producto_agregaratributo:
    path:  /producto/atributo/agregar/{id}
    defaults: { _controller: IncentivesCatalogoBundle:Producto:agregarAtributo, id: null }
    requirements:
        id:  \d+

producto_estadoprecio:
    path:  /producto/precio/estado/{id}
    defaults: { _controller: IncentivesCatalogoBundle:Producto:estadoPrecio, id: null }
    requirements:
        id:  \d+       

producto_editarprecio:
    path:  /producto/precio/editar/{id}
    defaults: { _controller: IncentivesCatalogoBundle:Producto:editarPrecio, id: null }
    requirements:
        id:  \d+

producto_catalogoproductoo:
    path:  /producto/catalogoproducto/{id}
    defaults: { _controller: IncentivesCatalogoBundle:Producto:catalogoproducto, id: null }
    
producto_buscar:
    path:  /producto/buscar
    defaults: { _controller: IncentivesCatalogoBundle:Producto:buscar}

cliente:
    path:  /cliente
    defaults: { _controller: IncentivesCatalogoBundle:Cliente:listado}

cliente_nuevo:
    path:  /cliente/nuevo
    defaults: { _controller: IncentivesCatalogoBundle:Cliente:nuevo}

cliente_editar:
    path:  /cliente/editar/{id}
    defaults: { _controller: IncentivesCatalogoBundle:Cliente:editar, id: null }
    requirements:
        id:  \d+

cliente_datos:
    path:  /cliente/datos/{id}
    defaults: { _controller: IncentivesCatalogoBundle:Cliente:datos, id: null }
    requirements:
        id:  \d+

cliente_estado:
    path:  /ciente/estado/{id}
    defaults: { _controller: IncentivesCatalogoBundle:Cliente:estado, id: null }
    requirements:
        id:  \d+

programa:
    path:  /programa
    defaults: { _controller: IncentivesCatalogoBundle:Programa:listado}

programa_nuevo:
    path:  /programa/nuevo/{id}
    defaults: { _controller: IncentivesCatalogoBundle:Programa:nuevo, id: null }

programa_editar:
    path:  /programa/editar/{id}
    defaults: { _controller: IncentivesCatalogoBundle:Programa:editar, id: null }
    requirements:
        id:  \d+

programa_datos:
    path:  /programa/datos/{id}
    defaults: { _controller: IncentivesCatalogoBundle:Programa:datos, id: null }
    requirements:
        id:  \d+

programa_estado:
    path:  /programa/estado/{id}
    defaults: { _controller: IncentivesCatalogoBundle:Programa:estado, id: null }
    requirements:
        id:  \d+

catalogo:
    path:  /catalogo
    defaults: { _controller: IncentivesCatalogoBundle:Catalogos:listado }

catalogo_nuevo:
    path:  /catalogo/nuevo/{id}
    defaults: { _controller: IncentivesCatalogoBundle:Catalogos:nuevo, id: null }

catalogo_editar:
    path:  /catalogo/editar/{id}
    defaults: { _controller: IncentivesCatalogoBundle:Catalogos:editar, id: null }
    requirements:
        id:  \d+

catalogo_datos:
    path:  /catalogo/datos/{id}
    defaults: { _controller: IncentivesCatalogoBundle:Catalogos:datos, id: null }
    requirements:
        id:  \d+

catalogo_estado:
    path:  /catalogo/estado/{id}
    defaults: { _controller: IncentivesCatalogoBundle:Catalogos:estado, id: null }
    requirements:
        id:  \d+

catalogo_aprobar:
    path:  /catalogo/aprobar/{id}/{resumido}
    defaults: { _controller: IncentivesCatalogoBundle:Catalogos:aprobar, id: null, resumido: null }
    requirements:
        id:  \d+

catalogo_aprobar_resumido:
    path:  /catalogo/aprobarresumido/{id}
    defaults: { _controller: IncentivesCatalogoBundle:Catalogos:aprobarresumido, id: null }
    requirements:
        id:  \d+

catalogo_galeria:
    path:  /catalogo/galeria/{id}/{vista}
    defaults: { _controller: IncentivesCatalogoBundle:Catalogos:galeria, id: null, vista: null }
    requirements:
        id:  \d+

catalogo_imagenes:
    path:  /catalogo/imagenes/{id}/{productos}
    defaults: { _controller: IncentivesCatalogoBundle:Catalogos:imagenes, id: null, productos: null }
    requirements:
        id:  \d+

catalogo_estadoaprobar:
    path:  /catalogo/aprobarcatalogo/{accion}/{id}/{catalogo}/{resumido}
    defaults: { _controller: IncentivesCatalogoBundle:Catalogos:aprobarcatalogo, accion: null, id: null, catalogo: null, resumido: null}

catalogo_indicadores:
    path:  /catalogo/indicadores/{id}
    defaults: { _controller: IncentivesCatalogoBundle:Catalogos:indicadores, id: null }
    requirements:
        id:  \d+

catalogo_navegar:
    path:  /catalogo/navegar
    defaults: { _controller: IncentivesCatalogoBundle:Catalogos:navegar}

producto_importar:
    path:  /producto/importar/
    defaults: { _controller: IncentivesCatalogoBundle:Producto:importar }

producto_exportar:
    path:  /producto/exportar/
    defaults: { _controller: IncentivesCatalogoBundle:Producto:exportar }

producto_formato:
    path:  /producto/formato/
    defaults: { _controller: IncentivesCatalogoBundle:Producto:formato }

producto_editar_mas:
    path:  /producto/editarmas/
    defaults: { _controller: IncentivesCatalogoBundle:Producto:editarmas }

producto_formato_edicion:
    path:  /producto/formatoeditar/
    defaults: { _controller: IncentivesCatalogoBundle:Producto:formatoeditarmas }

producto_formato_proveedor:
    path:  /producto/formatoproveedor/{id}
    defaults: { _controller: IncentivesCatalogoBundle:Producto:formatoporproveedor }


catalogo_intervalos:
    path:  /catalogo/intervalos/{id}
    defaults: { _controller: IncentivesCatalogoBundle:Catalogos:intervalos, id: null}
    
catalogo_intervaloseditar:
    path:  /catalogo/intervaloseditar/{id}
    defaults: { _controller: IncentivesCatalogoBundle:Catalogos:editarIntervalos, id: null}

catalogo_intervaloseliminar:
    path:  /catalogo/intervaloseliminar/{id}
    defaults: { _controller: IncentivesCatalogoBundle:Catalogos:eliminarIntervalos, id: null}

producto_referencia:
    path:  /producto/referencia/{id}
    defaults: { _controller: IncentivesCatalogoBundle:Producto:productoreferencia, id: null }
   
productos_proveedor:
    path:  /proveedores/productos/{id}
    defaults: { _controller: IncentivesCatalogoBundle:Catalogos:productosproveedor, id: null }

centrocostos:
    path:  /centrocostos
    defaults: { _controller: IncentivesCatalogoBundle:CentroCostos:listado}
    
centrocostos_nuevo:
    path:  /centrocostos/nuevo/{id}
    defaults: { _controller: IncentivesCatalogoBundle:CentroCostos:nuevo, id: null}

centrocostos_editar:
    path:  /centrocostos/editar/{id}
    defaults: { _controller: IncentivesCatalogoBundle:CentroCostos:editar, id: null }
    requirements:
        id:  \d+

centrocostos_datos:
    path:  /centrocostos/datos/{id}
    defaults: { _controller: IncentivesCatalogoBundle:CentroCostos:datos, id: null }
    requirements:
        id:  \d+
        
promociones:
    path:  /promociones
    defaults: { _controller: IncentivesCatalogoBundle:Promociones:listado}

promociones_nuevo:
    path:  /promociones/nuevo/{premio}
    defaults: { _controller: IncentivesCatalogoBundle:Promociones:nuevo, premio: null }

promociones_editar:
    path:  /promociones/editar/{promocion}
    defaults: { _controller: IncentivesCatalogoBundle:Promociones:editar, promocion: null }
    requirements:
        promocion:  \d+

promociones_datos:
    path:  /promociones/datos/{promocion}
    defaults: { _controller: IncentivesCatalogoBundle:Promociones:datos, promocion: null }
    requirements:
        promocion:  \d+

promociones_estado:
    path:  /promociones/estado/{promocion}
    defaults: { _controller: IncentivesCatalogoBundle:Promociones:estado, promocion: null }
    requirements:
        promocion:  \d+

promociones_catalogo:
    path:  /promociones/catalogo/{catalogo}
    defaults: { _controller: IncentivesCatalogoBundle:Promociones:listadoCatalogo, catalogo: null }
    requirements:
        catalogo:  \d+

premios_nuevo_producto:
    path:  /premios/nuevo/producto/{producto}
    defaults: { _controller: IncentivesCatalogoBundle:Premios:nuevoDesdeProducto, producto: null }

premios_editar_producto:
    path:  /premios/editar/producto/{premio}/{producto}
    defaults: { _controller: IncentivesCatalogoBundle:Premios:editarDesdeProducto, premio: null, producto: null }

premios_estado_producto:
    path:  /premios/estado/premio/{premio}/{producto}
    defaults: { _controller: IncentivesCatalogoBundle:Premios:estadoDesdeProducto, premio: null, producto: null }
    requirements:
        premio:  \d+ 

premios_maestro:
    path:  /premios/maestro
    defaults: { _controller: IncentivesCatalogoBundle:Premios:maestro }

premios_formatocambios:
    path:  /premios/formatocambios/{id}
    defaults: { _controller: IncentivesCatalogoBundle:Premios:formatoCambios, id: null }

premios_importar:
    path:  /premios/importar/{id}
    defaults: { _controller: IncentivesCatalogoBundle:Premios:importar }
    requirements:
        id:  \d+

premios_importar_combos:
    path:  /premios/importarcombos/{id}
    defaults: { _controller: IncentivesCatalogoBundle:Premios:importarCombos, id: null }

premios_exportar:
    path:  /premios/exportar/{id}
    defaults: { _controller: IncentivesCatalogoBundle:Premios:exportar }

premios_formato:
    path:  /premios/formato
    defaults: { _controller: IncentivesCatalogoBundle:Premios:formato }

premios_formato_combos:
    path:  /premios/formatocombos
    defaults: { _controller: IncentivesCatalogoBundle:Premios:formatoCombos }

premios_imagenes:
    path:  /premios/imagenes/{catalogo}
    defaults: { _controller: IncentivesCatalogoBundle:Catalogos:imagenesCatalogo, catalogo: null}
    requirements:
        catalogo:  \d+

premios_nuevo:
    path:  /premios/nuevo/{producto}/{catalogo}
    defaults: { _controller: IncentivesCatalogoBundle:Premios:nuevo, producto: null, catalogo: null }

premios_editar:
    path:  /premios/editar/{premio}
    defaults: { _controller: IncentivesCatalogoBundle:Premios:editar, premio: null }

premios_estado:
    path:  /premios/estado/{premio}
    defaults: { _controller: IncentivesCatalogoBundle:Premios:estado, premio: null }
    requirements:
        premio:  \d+ 

premios_listado:
    path:  /premios/listado/{catalogo}
    defaults: { _controller: IncentivesCatalogoBundle:Premios:listado, catalogo: null }

premios_combo_nuevo:
    path:  /premios/nuevocombo/{catalogo}
    defaults: { _controller: IncentivesCatalogoBundle:Premios:nuevoCombo, catalogo: null }

premios_combo_editar:
    path:  /premios/editarcombo/{premio}
    defaults: { _controller: IncentivesCatalogoBundle:Premios:editarCombo, premio: null }

premios_datos:
    path:  /premios/datos/{premio}
    defaults: { _controller: IncentivesCatalogoBundle:Premios:datos, premio: null }

